import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "./AntdRegistry";
import "./globals.css";
import { Layout, Menu, theme } from 'antd';
import { Header, Content, Footer } from 'antd/lib/layout/layout';
import Link from "next/link";


const items = new Array(4).fill(null).map((_, index) => ({
  key: `chart-${index + 1}`,
  label: <Link href={`/chart-${index + 1}`}>{`Chart ${index + 1}`}</Link>,
}));

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kool Charts",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </head>
    <body>
    <Layout style={{minHeight: '100vh'}}>
      <Header
        style={{
          position: 'sticky',
          top: 0,
          zIndex: 1,
          width: '100%',
          display: 'flex',
          alignItems: 'center',
        }}
      >
        <div className="demo-logo"        
          style={{
            color: 'white',
            fontWeight: 'bolder',
            marginRight: '16px'
          }}
        >
          <Link href="/">KoolCharts</Link>
        </div>
        <Menu
          theme="dark"
          mode="horizontal"
          defaultSelectedKeys={['2']}
          items={items}
          style={{ flex: 1, minWidth: 0 }}
        />
      </Header>
      <Content style={{ padding: '0 48px'}}>
      <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </Content>
      <Footer style={{ textAlign: 'center' }}>
        KoolCharts ©{new Date().getFullYear()} Created by jbin with Antd, Antv/G2
      </Footer>
    </Layout>
    
    </body>
    </html>

  );
}

export default RootLayout;
